const won=n=>Math.round(Number(n)||0).toLocaleString('ko-KR')+'원';
const num=id=>Math.max(0,Number(document.getElementById(id).value)||0);
function jump(id){document.getElementById(id).scrollIntoView({behavior:'smooth',block:'start'})}
function serviceDays(a,b){const s=new Date(a),e=new Date(b);const ms=e-s;return ms>=0?Math.floor(ms/86400000)+1:0}
function severanceEstimate(start,end,wage,days){const d=serviceDays(start,end);if(d<365)return {days:d,avg:wage/Math.max(1,days),sev:0};const avg=wage/Math.max(1,days);return {days:d,avg,sev:avg*30*(d/365)}}
function calcInsurance(){const gross=num('grossPay'),nonTax=num('nonTax'),base=Math.max(0,gross-nonTax);const pensionBase=base===0?0:Math.min(6590000,Math.max(410000,base));const pension=pensionBase*.0475,health=base*.040674,employment=base*.009,total=pension+health+employment;pensionOut.textContent=won(pension);healthOut.textContent=won(health);employmentOut.textContent=won(employment);insuranceTotal.textContent=won(total);afterInsurance.textContent=won(Math.max(0,gross-total))}
function calcMinWage(){const hourly=num('hourly'),hours=Math.min(40,num('weeklyHours')),rest=hours>=15?(hours/40)*8:0,weekly=hourly*(hours+rest),monthly=weekly*(365/7/12);weeklyPaidRest.textContent=rest.toFixed(1)+'시간';weeklyPay.textContent=won(weekly);monthlyPay.textContent=won(monthly);minWageStatus.textContent=hourly>=10320?'2026년 최저시급 이상입니다.':'2026년 최저시급 10,320원보다 낮습니다.'}
function calcWeeklyHoliday(){const rate=num('weeklyRate'),hours=Math.min(40,num('weeklyWorkHours')),rest=hours>=15?(hours/40)*8:0;holidayHours.textContent=rest.toFixed(1)+'시간';holidayPay.textContent=won(rate*rest)}
function calcAnnualLeave(){annualLeaveOut.textContent=won(num('unusedLeave')*num('dailyOrdinary'))}
function calcOvertime(){overtimeOut.textContent=won(num('ordinaryHourly')*num('overtimeHours')*Number(overtimeMultiplier.value))}
function calcAnnual(){salaryConvertOut.textContent=won(num('monthlySalary')*12)}
function calcMonthly(){salaryConvertOut.textContent=won(num('annualSalary')/12)}
function calcSeverance(){const r=severanceEstimate(startDate.value,endDate.value,num('threeMonthWage'),num('threeMonthDays'));serviceDays.textContent=r.days.toLocaleString('ko-KR')+'일';avgDaily.textContent=won(r.avg);severanceOut.textContent=r.days>=365?won(r.sev):'계속근로 1년 미만'}
function calcQuitPack(){const s=num('quitSeverance'),l=num('quitLeaveDays')*num('quitDailyWage');quitSevOut.textContent=won(s);quitLeaveOut.textContent=won(l);quitTotalOut.textContent=won(s+l)}
function calcQuitQuick(){const r=severanceEstimate(qStart.value,qEnd.value,num('qThreeMonth'),num('qDays')),leave=num('qUnusedLeave')*num('qDailyWage'),total=r.sev+leave;qTotal.textContent=r.days>=365?won(total):won(leave);qBreakdown.textContent='퇴직금 '+(r.days>=365?won(r.sev):'1년 미만')+' + 연차수당 '+won(leave)}
window.addEventListener('DOMContentLoaded',()=>{calcInsurance();calcMinWage();calcWeeklyHoliday();calcAnnualLeave();calcOvertime();calcAnnual();calcSeverance();calcQuitPack();calcQuitQuick()});